### ISSUE TITLE
Long url path causes Http 500

### ISSUE THREAD

**Issue by thenewguy** [jazzband/django-silk#312]
I've encountered an issue with very long urls.  In this particular case I am using ptrack.  The middleware is raising `DataError ... value too long for type character varying(190)`

I would not expect silk to cause my site to stop serving pages.  At the very least the error should be caught and suppressed.  But it would be nice to be able to capture the silk profiling data as well.

**Comment by smaccona** [comment]
We can blame MySQL for this because we had to limit the model for that field to 190 characters in order to be able to create MySQL indexes on it (see #38 for a prolonged discussion).

I agree that this shouldn't cause a 500 error, and Silk should gracefully handle URLs that are longer than 190 characters. I will open a PR.

**Comment by smaccona** [comment]
Closing this in favor of #179.
