### ISSUE TITLE
Proposal: Drop dependency on pytz in favor of zoneinfo

### ISSUE THREAD

**Issue by aDramaQueen** [jazzband/django-silk#581]
Hi,
pytz is/was a good llibrary. But it's obsolete since [PEP 615](https://peps.python.org/pep-0615/). In the long run, you should not use this 3rd party package, but the language integrated functionality.
Even big frameworks like Django [(Django 4.0 Release Info)](https://docs.djangoproject.com/en/4.0/releases/4.0/#what-s-new-in-django-4-0) already dropped pytz.

**Comment by albertyw** [comment]
Yep, we should probably switch from pytz to zoneinfo, but zoneinfo is only part of the standard library as of python 3.9.  Python 3.8 will continue to receive security updates until 2024-10 so that means [backports.zoneinfo](https://pypi.org/project/backports.zoneinfo/) will be needed for a while.  This is also what Django is doing to maintain compatibility with older python versions.

**Comment by albertyw** [comment]
Actually, on second review, it seems the pytz package is only used for `pytz.UTC` which should be trivially replaceable with `datetime.timezone.UTC` (https://docs.python.org/3.7/library/datetime.html#datetime.timezone.utc).  We might not need either pytz nor zoneinfo.
