### ISSUE TITLE
Using profiler with a WSGI app

### ISSUE THREAD

**Issue by kunalgrover05** [jazzband/django-silk#78]
I want to use it with a WSGI server(which runs besides a Django server). I tried writing a wrapper for converting this middleware to a WSGI middleware, but didn't succeed. Any hints on that? Also, will Silk work properly in that case?

**Comment by mtford90** [comment]
Silk is very much tied to Django right now - the quickest way to do what you want would be to tie into Silk's django models in the same fashion as `DataCollector` and the silk middleware, filling in the fields as necessary. You'd also need to tie in the silk meta profiler if you use that (which calculates any increased response time caused by silk)
